In [2]:
import pandas as pd
import os

# Subsetting

Review core methods to select data from a `pandas.DataFrame`.

See information about the data on [course website](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.html).

## Learning objectives
By the end of this lesson, students will be able to:

- Choose appropriate methods for selecting rows and columns from a `pandas.DataFrame`
- Construct conditions to subset rows
- Describe the difference between label-based subsetting and position-based subsetting
- Apply best practices when using `iloc` and `loc` selection

## Read in a CSV

To read in a CSV file into our Python workspace we will first use the `os` package to create a reproducible file path:

In [3]:
fp = os.path.join('data','wetlands_seasonal_bird_diversity.csv')
df = pd.read_csv(fp)
df.head()
df.dtypes

year            int64
CSM_winter    float64
CSM_spring    float64
CSM_fall      float64
MUL_winter    float64
MUL_spring    float64
MUL_fall      float64
SDW_winter    float64
SDW_spring    float64
SDW_fall      float64
TJE_winter    float64
TJE_spring    float64
TJE_fall      float64
dtype: object

`os` is a package that provides functions for interacting with the operating system, allowing us to perform tasks like file manipulation in a platform-independent way.

`os.path.join()`: create file paths that work on any operating system, making your code more portable.

Birds were surveyed in four wetlands:

- Carpinteria Salt Marsh (CSM)
- Mugu Lagoon (MUL), 
- San Dieguito Wetland (SDW)
- Tijuana Estuary (TJE). 

Values from second column to last column = number of different bird species recorded across the survey sites in each wetland during winter, spring, and fall of a given year. 

`year` column = year in which the data was collected. 

*Example: the `CSM_fall` column has the number of species recorded in fall at Carpinteria Salt Marsh across years.*

*Surveys occurred yearly from 2010 to 2023.*

High-level information about the df:

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
9,2019,39.0,39.0,40.0,57.0,52.0,53.0,54.0,55.0,53.0,63.0,54.0,50.0
10,2020,46.0,NaN,47.0,56.0,NaN,66.0,57.0,NaN,58.0,54.0,40.0,54.0
11,2021,47.0,44.0,53.0,54.0,55.0,60.0,57.0,58.0,57.0,53.0,68.0,51.0
12,2022,40.0,46.0,49.0,60.0,55.0,65.0,57.0,60.0,57.0,60.0,61.0,60.0
13,2023,56.0,43.0,36.0,72.0,59.0,53.0,64.0,63.0,33.0,60.0,56.0,38.0

Index(['year', 'CSM_winter', 'CSM_spring', 'CSM_fall', 'MUL_winter',
       'MUL_spring', 'MUL_fall', 'SDW_winter', 'SDW_spring', 'SDW_fall',
       'TJE_winter', 'TJE_spring', 'TJE_fall'],
      dtype='object')

year            int64
CSM_winter    float64
CSM_spring    float64
CSM_fall      float64
MUL_winter    float64
MUL_spring    float64
MUL_fall      float64
SDW_winter    float64
SDW_spring    float64
SDW_fall      float64
TJE_winter    float64
TJE_spring    float64
TJE_fall      float64
dtype: object

In [ ]:
df.shape

(14, 13)

## Selecting a single column

Simplest case: Selecting a single column by column name.

General syntax:




#### Example 
Select the number of bird species observed at the Mugu Lagoon in spring.

In [41]:
df['MUL_spring'].count()
type(df.MUL_spring)
type(df['CSM_fall'])

pandas.core.series.Series

Since we only selected a single column, `mul_spring` is a `pandas.Series`:

In [ ]:
(type(df['MUL_spring']))

pandas.core.series.Series

Recall: We can think of a `pandas.DataFrame` as a dictionary of its columns.
Then, we can access a single column using the column name as the key, just like we would do in a dictionary: `df['column_name']`.



For example:

In [ ]:
print(df['MUL_spring'])

0      NaN
1     52.0
2     58.0
3     58.0
4     52.0
5     50.0
6     48.0
7     54.0
8     54.0
9     52.0
10     NaN
11    55.0
12    55.0
13    59.0
Name: MUL_spring, dtype: float64




In general, it is better to use the `df['column_name']` syntax. Why?


## Selecting multiple columns...

### ... using a list of column names

Select multiple columns in a single call by passing a list with the column names to the square brackets `[]`:




## Check-in
Is this an example of label-based selection or location-based selection?

#### Example
Look at the species in the Tijuana Estuary during winter and fall:

In [26]:
tje_wf = df[['TJE_winter','TJE_fall']]

# label based selection

## Check-in
What is the type and shape of the `tje_wf` output? Verify your answer.

In [28]:
print(type(tje_wf))
tje_wf.shape

<class 'pandas.core.frame.DataFrame'>

(14, 2)


### ... using a slice

To select a slice of the columns we will use a special case of **`loc` selection**. General syntax:

Notice:

- the first value passed to `loc` is used for selecting rows, using a colon `:` as the row-selection parameter means "select all the rows"

- the slice of the data frame we'll obtain includes both endpoints of the slice `'column_start':'column_end'`. 


#### Example

Select the slice of columns that covers data from CSM and Mugu Lagoon.

In [13]:
df

csm_mul = df.loc[:, 'CSM_winter':'MUL_fall' ]

# Select all columns that have fall in it
df.filter(like = 'fall')

df.filter(like = 'MUL')

    MUL_winter  MUL_spring  MUL_fall
0         45.0         NaN      61.0
1         58.0        52.0       NaN
2         57.0        58.0      53.0
3         60.0        58.0      62.0
4         49.0        52.0      57.0
5         58.0        50.0      51.0
6         63.0        48.0      58.0
7         57.0        54.0      53.0
8         56.0        54.0      57.0
9         57.0        52.0      53.0
10        56.0         NaN      66.0
11        54.0        55.0      60.0
12        60.0        55.0      65.0
13        72.0        59.0      53.0

## Selecting rows...
Let's move on to selecting rows. 

### ... using a condition
To select rows that satisfy a particular condition the general syntax is 




#### Example

We are interested in all data after 2020.

In [51]:
post2020 = df[df['year'] > 2020]

*Let's break down what is happening here.*

In [ ]:
df['year'] > 2020

When we pass such a series of boolean values to the selection brackets `[]` we keep only the rows that correspond to a `True` value. 


## Check-in
 Get the subset of the data frame on which the San Dieguito Wetland has at least 75 species recorded during spring.

In [35]:
df

df[df['SDW_spring'] >= 75]

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
0,2010,39.0,40.0,50.0,45.0,NaN,61.0,NaN,75.0,85.0,NaN,NaN,81.0
4,2014,38.0,43.0,45.0,49.0,52.0,57.0,61.0,78.0,71.0,60.0,81.0,62.0

 

#### Example

Suppose we want to look at data from years 2012 to 2015 (including both years). One way of doing this is to use the `between` operator in our condition:

In [40]:
df[df['year'].between(2012,2015)]

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
2,2012,51.0,43.0,49.0,57.0,58.0,53.0,71.0,72.0,73.0,70.0,63.0,69.0
3,2013,42.0,46.0,38.0,60.0,58.0,62.0,69.0,70.0,70.0,69.0,74.0,64.0
4,2014,38.0,43.0,45.0,49.0,52.0,57.0,61.0,78.0,71.0,60.0,81.0,62.0
5,2015,44.0,42.0,45.0,58.0,50.0,51.0,71.0,61.0,65.0,73.0,76.0,64.0

### ... using multiple conditions
We can combine multiple conditions to select rows by surrounding each one in parentheses `()` and using the or operator `|` and the and operator `&`.

#### Example: or 

Select rows in which the CSM has more than 50 species registered in winter *or* fall:

In [38]:
df[(df['CSM_winter'] > 50) | (df['CSM_fall'] > 50)]

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
2,2012,51.0,43.0,49.0,57.0,58.0,53.0,71.0,72.0,73.0,70.0,63.0,69.0
11,2021,47.0,44.0,53.0,54.0,55.0,60.0,57.0,58.0,57.0,53.0,68.0,51.0
13,2023,56.0,43.0,36.0,72.0,59.0,53.0,64.0,63.0,33.0,60.0,56.0,38.0

#### Example: and

Select rows in which both the Carpinteria Salt Marsh and the San Dieguito Wetland have more than 60 reported bird species during spring:

In [39]:
df[(df['CSM_spring'] > 60 ) & (df['SDW_spring'] >60)]

Empty DataFrame
Columns: [year, CSM_winter, CSM_spring, CSM_fall, MUL_winter, MUL_spring, MUL_fall, SDW_winter, SDW_spring, SDW_fall, TJE_winter, TJE_spring, TJE_fall]
Index: []


### ... by position

Sometimes we may want to select certain rows depending on their *actual position* in the data frame. In other words, using **position-based subsetting**.  


#### Example

In [48]:
df.iloc[4]

year          2014.0
CSM_winter      38.0
CSM_spring      43.0
CSM_fall        45.0
MUL_winter      49.0
MUL_spring      52.0
MUL_fall        57.0
SDW_winter      61.0
SDW_spring      78.0
SDW_fall        71.0
TJE_winter      60.0
TJE_spring      81.0
TJE_fall        62.0
Name: 4, dtype: float64

In [59]:
df.iloc[9:14]
df.iloc[[4]] # double brackets creates a df
df.iloc[4] # single brackets gives you a series

year          2014.0
CSM_winter      38.0
CSM_spring      43.0
CSM_fall        45.0
MUL_winter      49.0
MUL_spring      52.0
MUL_fall        57.0
SDW_winter      61.0
SDW_spring      78.0
SDW_fall        71.0
TJE_winter      60.0
TJE_spring      81.0
TJE_fall        62.0
Name: 4, dtype: float64

### Example

Our `post_2020` subset kept the original row labels from `df`: 11, 12, and 13.

In [62]:
post2020.iloc[0]
post2020.set_index('year')

# select first row by label (index)

post2020.loc[[11]]

# post2020.loc[0]  this doesnt work because there is no '0' index

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
11,2021,47.0,44.0,53.0,54.0,55.0,60.0,57.0,58.0,57.0,53.0,68.0,51.0

year          2021.0
CSM_winter      47.0
CSM_spring      44.0
CSM_fall        53.0
MUL_winter      54.0
MUL_spring      55.0
MUL_fall        60.0
SDW_winter      57.0
SDW_spring      58.0
SDW_fall        57.0
TJE_winter      53.0
TJE_spring      68.0
TJE_fall        51.0
Name: 11, dtype: float64

year          2021.0
CSM_winter      47.0
CSM_spring      44.0
CSM_fall        53.0
MUL_winter      54.0
MUL_spring      55.0
MUL_fall        60.0
SDW_winter      57.0
SDW_spring      58.0
SDW_fall        57.0
TJE_winter      53.0
TJE_spring      68.0
TJE_fall        51.0
Name: 11, dtype: float64

Both return the 2021 row. `iloc` counts positions starting from 0, while `loc` uses the labels in the index. That's why `post_2020.loc[0]` raises a `KeyError`: there is no row labeled 0 in `post_2020`.

In [63]:
# post2020.loc[0] gives an error because there is no index 0

## Selecting rows and columns simultaneously...

Can be done using `loc` (labels) or `iloc` (positions).

### ...by labels or conditions
When we want to select rows and columns simultaneously by labels (including using conditions) we can use `loc` selection with the syntax 



#### Example

Select winter surveys for Mugu Lagoon and Tijuana Estuary after 2020:

In [64]:
df.iloc[df['year'] >2020, ['MUL_winter','TJE_winter']]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

Let's break down this code:

- using the `df.loc[ row-selection , column-selection]` syntax

- `row-selection` parameter = condition `df['year']>2020`, which is a boolean array saying which years are greater than 2020

- `column-selection` parameter = `['MUL_winter','TJE_winter']`, which is a list with the names of the two columns we are interested in. 


### ... by position

When we want to select rows and columns simultaneously by position we use `iloc` selection with the syntax:


#### Example

Suppose we want to select rows 3-7 (including 7) and columns 3 and 4:

In [66]:
df.iloc[3:7,3:5]

   CSM_fall  MUL_winter
3      38.0        60.0
4      45.0        49.0
5      45.0        58.0
6      47.0        63.0

Let's break it down:

- we are using the `df.iloc[ row-indices , column-indices]` syntax to select by position

- the `row-indices` parameter is the slice *of integer indices* 3:8. Remember the right endpoint (8) won't be included.

- the `column-indices` parameter is the list of integer indices 3 and 4. This means we are selecting the fourth and fifth column.

## Notes about `loc` and `iloc`

## `iloc` vs. `loc`: which one does what?
*At the beginning, the difference between `iloc` and `loc` can be confusing.*

Remember the `i` in `iloc` stands for *integer location*, so `iloc` only uses integer indexing to retrieve information from the data frames in the same way as indexing for Python lists.

## `iloc` for column selection? Think about it.
We can also access columns by position using `iloc` - but it is best not to if possible.

Example:

Suppose we want to access the 9th column in the df - then we want to select a column *by position*. In this case, the 9th column is the data at San Dieguito Wetland during spring and the 9th position corresponds to the index 8.

In [ ]:
# Select column by position using iloc
# The syntax is iloc[row-indices, column-indices]
# [:,8] means "select all rows from the column at index 8"
sdw_spring = df.iloc[:,8]
sdw_spring.head()

0    75.0
1    74.0
2    72.0
3    70.0
4    78.0
Name: SDW_spring, dtype: float64

Unless you are *really* looking for information about the "first column", **do not access a column by position**. This can break in many ways:

- it relies on a person correctly counting the position of a column. Even with a small dataset this can be prone to error.

- it is not explicit: if we want information about SDW during spring, `df.SDW_spring` or `df['SDW_spring']` are explicitly telling us we are accessing that information. `df.iloc[:,8]` is obscure and uninformative.

- datasets can get updated. Maybe a new column was added before `SDW_spring`, changing the position of the column and making any code depending on `df.iloc[:,8]` invalid. 

**Accessing columns by labels helps reproducibility!**